// Textos de autorizaciones legales del formulario de Bancamía
// Extraídos del formulario oficial de Google Forms

export const autorizacionTratamientoDatos = `Autorizo de manera expresa y previa al BANCO DE LAS MICROFINANZAS, en adelante BANCAMÍA S.A., o a quien en el futuro adquiera o represente a cualquier título, para que efectúe el tratamiento de mis datos personales, incluyendo datos biométricos, de la manera y para las finalidades que se señalan a continuación:

A. Para que se obtenga, trate, consulte, recolecte, comparta, almacene, transmita, transfiera, informe, reporte, intercambie, venda, rectifique, procese, elimine, modifique, actualice, aclare, retire o divulgue y en general, efectúe cualquier operación o conjunto de operaciones sobre mis Datos Personales, recolectados u obtenidos de manera física, digital, electrónica, telefónica y/o por cualquier medio que pueda ser objeto de consulta, lo anterior, para conocimiento de mi perfil comercial, transaccional, e información referente a mis datos personales que reposen o estén contenidos en bases de datos o archivos de cualquier Entidad Pública o privada, tanto del sector real como del financiero, entre otros, los Ministerios, Entes de Control, los Departamentos Administrativos, la DIAN, Fiscalía General de la Nación, operadores de Información del PILA y parafiscales, Administradoras de Fondos de Pensiones y Cesantías, Registraduría Nacional del Estado Civil, Juzgados, tribunales, altas Cortes, información financiera, comercial y crediticia ante cualquier operador de información o administrador de bases de datos en Colombia o en el exterior, todo esto, con el objetivo de poder desarrollar análisis de riesgo, estudios de mercado, investigaciones, desarrollo de conocimiento del cliente, estadísticas, cumplimiento de la normatividad aplicable a la evasión fiscal, al Sistema de Administración de Riesgo de Lavado de Activos y Financiación del Terrorismo, prevención de conductas delictivas y en general cualquier tipo de riesgo.

B. Autorizo a que se me contacte vía telefónica, por correo electrónico o físico, SMS, mensajes PUSH, redes sociales como Facebook, Twitter, Instagram o similares, servicios de mensajería instantánea como WhatsApp y Facebook Messenger o por cualquier otro medio, con la finalidad de:
1. Administrar nuestra relación comercial, ya sea directamente o a través de terceros.
2. Ofrecerme productos y servicios.
3. Actualizar mis datos personales.
4. Establecer acuerdos de pago.
5. Realizar gestión de cobranza judicial, extrajudicial y gestiones conexas para obtener el pago de mis obligaciones.
6. Recibir información del trámite de PQR
7. Evaluaciones de servicio, encuestas de satisfacción, encuestas de conocimiento, ofrecimiento u experimentación de nuevos productos y/o servicios, ofrecimiento de propuestas de valor adicionales a las que el Banco está en capacidad de ofrecerme de manera autónoma, implementación de una oferta, celebración de convenios de marca compartida, elaboración y/o reporte de información estadística, estudios o análisis de mercado, investigación sobre bienes y derechos, archivo, implementación de software y servicios tecnológicos respecto de cualquiera de los productos y/o servicios ofrecidos por BANCAMIA S.A, o por cualquiera de las entidades autorizadas y/o sus aliados comerciales durante el desarrollo de la etapa precontractual, contractual y pos contractual, o respecto de cualquier relación negocial subyacente que tenga con el mismo.

Sin perjuicio de lo anterior, reconozco el derecho que me asiste para revocar en los términos que prevé la ley, la autorización que he otorgado para:
1. Envío de ofertas comerciales.
2. Envío de oferta comercial de productos que no posea con BANCAMIA S.A.
3. Compartir información con terceros aliados para que estos ofrezcan productos y servicios.

C. Autorizo la verificación de multas y sanciones ante autoridades administrativas y judiciales, a dar cumplimiento de la legislación colombiana o extranjera, al cumplimiento de las órdenes de autoridades judiciales o administrativas, y a compartir información para que pueda ser utilizada como medio de prueba en el desarrollo de un proceso judicial.

D. (Ley 1266 de 2008). Autorizo a consultar, reportar, actualizar y/o retirar ante las Centrales de Información Financiera, la información relativa a mis datos de contacto y ubicación, inicio, ejecución y extinción de mis obligaciones vigentes o vencidas sin cancelar, y a mi comportamiento o hábitos de pago derivados de cualquier relación comercial o financiera que tenga, haya tenido o llegue a tener. Así mismo, soy consciente de que en el evento en que incumpla cualquiera de las obligaciones que adquiera frente a Bancamía ya sea en mi calidad de titular, deudor, codeudor, de alguno de los productos de su portafolio dicha información podrá ser interpretada como negativa, y podrá generar consecuencias perjudiciales para mi acceso al crédito y a otros productos o servicios ofrecidos por personas naturales o jurídicas, entidades públicas o privadas; tanto del sector real como del financiero.

E. Autorizo a tratar mis datos personales o de mi representada registrados en el Portal Transaccional o Bancamóvil, a través de los cuales será posible conocer el número de ID del dispositivo móvil utilizado, información de red, información sobre las acciones adelantadas en la aplicación, la fecha y hora de tales acciones, como la dirección IP y/o las coordenadas de geolocalización /GPS asignadas a mi dispositivo móvil por el tercero proveedor de acceso a internet, a fin de conocer mi localización, detectar y/o prevenir fraudes, funciones de grabación de voz, acceso a la galería de imágenes de mi dispositivo, información de app instaladas, conocer el consumo de datos, tipo de teléfono, incluyendo aquellos que puedan llegar a ser clasificados como sensibles (datos biométricos que se requieran para el uso de la aplicación como por ejemplo mi huella dactilar, mi fotografía o voz), correo electrónico, mi firma digital, número de móvil, mis datos económicos y financieros recolectados, uso de cookies, entre otros. Todo lo anterior, dentro del marco de la configuración de seguridad y privacidad que como usuario le asigne a la plataforma y/o al dispositivo móvil según sea el caso.

F. Autorizo a monitorear, grabar, almacenar y conservar las llamadas telefónicas o cualquier otra comunicación electrónica que tenga con BANCAMÍA S.A, con el propósito de administrar y evaluar cualquier tipo de riesgo durante la vigencia del vínculo contractual.

G. De manera particular, con la imposición de mis huellas digitales a través de medios electrónicos, autorizo de manera expresa y previa al Banco para que valide mis huellas digitales, esto con la finalidad de que a través de una entidad certificada como operador biométrico o de manera directa, realice la validación de mi identidad contra la base de datos que produce y administra la Registraduría Nacional del Estado Civil ("RNEC"). En relación con esta autorización, manifiesto que he sido informado de manera clara y previa a la imposición de mis huellas digitales a través de medios electrónicos, acerca de lo siguiente:
1. Que el suministro de mis huellas digitales, es facultativo y no obligatorio.
2. Que las huellas digitales se entienden como datos personales sensibles, razón por la cual se requiere de mi autorización explícita para el tratamiento de las mismas. La presente autorización incluye tomar mi huella digital (dato sensible) y administrarla con el fin de facilitar mi vinculación a BANCAMÍA S.A; el manejo de los productos que adquiera; y en especial validar mi identidad en la realización de transacciones. En todo caso, mi huella digital no podrá ser vendida, distribuida, transferida o cedida a terceros, salvo que medie orden de autoridad competente en ese sentido.

H. Me comprometo frente a BANCAMÍA S.A a suministrar información cierta, y a actualizar mi información personal y de contacto con la periodicidad que él o la ley exijan, pero cuando menos una vez cada año.`;

export const autorizacionContacto = `Acepto ser contactado a través de WhatsApp, SMS, mail y llamadas, para el ofrecimiento de productos y servicios.`;

