// Lista completa de ciudades de negocio de Bancamía
// Extraída del formulario oficial de Google Forms

export interface CiudadNegocio {
  codigo: string;
  nombre: string;
}

export const ciudadesNegocio: CiudadNegocio[] = [
  { codigo: "201", nombre: "Plaza Minorista" },
  { codigo: "202", nombre: "Kennedy" },
  { codigo: "203", nombre: "Quirigua" },
  { codigo: "204", nombre: "Soacha" },
  { codigo: "205", nombre: "Restrepo" },
  { codigo: "206", nombre: "Fusagasuga" },
  { codigo: "207", nombre: "Toberin" },
  { codigo: "208", nombre: "Suba Villamaria" },
  { codigo: "209", nombre: "Funza" },
  { codigo: "210", nombre: "Girardot" },
  { codigo: "211", nombre: "Av. Caracas" },
  { codigo: "212", nombre: "Mesitas" },
  { codigo: "213", nombre: "Yomasa" },
  { codigo: "214", nombre: "Patio Bonito" },
  { codigo: "215", nombre: "Tunja" },
  { codigo: "216", nombre: "Centro Medellín" },
  { codigo: "217", nombre: "Bello" },
  { codigo: "219", nombre: "Itagui" },
  { codigo: "220", nombre: "Manizales" },
  { codigo: "221", nombre: "Castilla" },
  { codigo: "222", nombre: "Manrique" },
  { codigo: "223", nombre: "Rionegro" },
  { codigo: "224", nombre: "Bosa" },
  { codigo: "225", nombre: "Fontibon" },
  { codigo: "227", nombre: "Santa Helenita" },
  { codigo: "228", nombre: "Suba Rincon" },
  { codigo: "229", nombre: "Venecia" },
  { codigo: "230", nombre: "Envigado" },
  { codigo: "231", nombre: "La Dorada" },
  { codigo: "233", nombre: "La Victoria" },
  { codigo: "234", nombre: "Belen" },
  { codigo: "235", nombre: "Santo Domingo" },
  { codigo: "237", nombre: "Chinchina" },
  { codigo: "238", nombre: "Sogamoso" },
  { codigo: "239", nombre: "Apartado" },
  { codigo: "240", nombre: "Molinos" },
  { codigo: "241", nombre: "Caldas" },
  { codigo: "242", nombre: "Carmen de Viboral" },
  { codigo: "243", nombre: "Zipaquira" },
  { codigo: "244", nombre: "Facatativa" },
  { codigo: "246", nombre: "Buenos Aires" },
  { codigo: "247", nombre: "La Libertad" },
  { codigo: "248", nombre: "Caucasia" },
  { codigo: "249", nombre: "Andes" },
  { codigo: "252", nombre: "Chiquinquira" },
  { codigo: "253", nombre: "Turbo" },
  { codigo: "254", nombre: "Duitama" },
  { codigo: "255", nombre: "Copacabana" },
  { codigo: "256", nombre: "Chia" },
  { codigo: "257", nombre: "Engativa" },
  { codigo: "258", nombre: "Pedregal" },
  { codigo: "259", nombre: "Marinilla" },
  { codigo: "260", nombre: "San Fernando" },
  { codigo: "261", nombre: "Moniquira" },
  { codigo: "262", nombre: "Barrancas" },
  { codigo: "263", nombre: "Carepa" },
  { codigo: "264", nombre: "El Bagre" },
  { codigo: "265", nombre: "Planeta Rica" },
  { codigo: "266", nombre: "Primero de Mayo" },
  { codigo: "267", nombre: "Villeta" },
  { codigo: "268", nombre: "Monteria" },
  { codigo: "269", nombre: "Ubate" },
  { codigo: "270", nombre: "San Juan" },
  { codigo: "271", nombre: "Principal" },
  { codigo: "272", nombre: "Sahagun" },
  { codigo: "273", nombre: "Sincelejo" },
  { codigo: "274", nombre: "Cartagena" },
  { codigo: "275", nombre: "Perdomo" },
  { codigo: "277", nombre: "Yopal" },
  { codigo: "278", nombre: "Ocaña" },
  { codigo: "280", nombre: "Garagoa" },
  { codigo: "281", nombre: "La Ceja" },
  { codigo: "282", nombre: "Pamplona" },
  { codigo: "283", nombre: "Galan" },
  { codigo: "284", nombre: "Centro Suba" },
  { codigo: "285", nombre: "Armenia" },
  { codigo: "287", nombre: "Pereira" },
  { codigo: "288", nombre: "Santa Rosa de Cabal" },
  { codigo: "289", nombre: "Cucuta Centro" },
  { codigo: "290", nombre: "San Gil" },
  { codigo: "291", nombre: "Magangue" },
  { codigo: "292", nombre: "Barranquilla" },
  { codigo: "294", nombre: "Aguachica" },
  { codigo: "295", nombre: "Cucuta Atalaya" },
  { codigo: "296", nombre: "Valledupar" },
  { codigo: "297", nombre: "Mariquita" },
  { codigo: "299", nombre: "Arauca" },
  { codigo: "300", nombre: "Agustin Codazzi" },
  { codigo: "301", nombre: "Cartago" },
  { codigo: "302", nombre: "Maicao" },
  { codigo: "303", nombre: "Ibague" },
  { codigo: "305", nombre: "Montelíbano" },
  { codigo: "306", nombre: "Quibdo" },
  { codigo: "307", nombre: "Villavicencio" },
  { codigo: "308", nombre: "Montería Centro" },
  { codigo: "310", nombre: "Pitalito" },
  { codigo: "311", nombre: "El Banco" },
  { codigo: "312", nombre: "Tumaco" },
  { codigo: "313", nombre: "Puerto Asis" },
  { codigo: "314", nombre: "Florencia" },
  { codigo: "315", nombre: "Garzon" },
  { codigo: "316", nombre: "Riohacha" },
  { codigo: "317", nombre: "Palmira" },
  { codigo: "318", nombre: "Tulua" },
  { codigo: "319", nombre: "Puerto Berrio" },
  { codigo: "320", nombre: "Barrancabermeja" },
  { codigo: "322", nombre: "Buenaventura" },
  { codigo: "323", nombre: "Fundacion" },
  { codigo: "324", nombre: "San Jose del Guaviare" },
  { codigo: "327", nombre: "Buga" },
  { codigo: "329", nombre: "Santander de Quilichao" },
  { codigo: "330", nombre: "Puerto Boyaca" },
  { codigo: "331", nombre: "Plato" },
  { codigo: "332", nombre: "Libano" },
  { codigo: "333", nombre: "Yumbo" },
  { codigo: "334", nombre: "Ipiales" },
  { codigo: "336", nombre: "Urrao" },
  { codigo: "337", nombre: "Yarumal" },
  { codigo: "338", nombre: "Chaparral" },
  { codigo: "339", nombre: "Riosucio" },
  { codigo: "340", nombre: "Pasto" },
  { codigo: "341", nombre: "Santafe de Antioquia" },
  { codigo: "342", nombre: "La Union (Valle)" },
  { codigo: "343", nombre: "Corozal" },
  { codigo: "344", nombre: "San Marcos" },
  { codigo: "345", nombre: "Granada" },
  { codigo: "347", nombre: "Malaga" },
  { codigo: "350", nombre: "La Union" },
  { codigo: "352", nombre: "Mocoa" },
  { codigo: "353", nombre: "Cimitarra" },
  { codigo: "354", nombre: "Florida" },
  { codigo: "355", nombre: "Jamundi" },
  { codigo: "356", nombre: "Tierralta" },
  { codigo: "357", nombre: "Bosconia" },
  { codigo: "359", nombre: "Cerrito" },
  { codigo: "360", nombre: "Cienaga de Oro" },
  { codigo: "361", nombre: "Orito" },
  { codigo: "362", nombre: "La Plata" },
  { codigo: "365", nombre: "San Bernardo" },
  { codigo: "368", nombre: "Puerto Inírida" },
  { codigo: "369", nombre: "Mitu" },
  { codigo: "370", nombre: "San Andres de Sotavento" },
  { codigo: "371", nombre: "Moñitos" },
  { codigo: "372", nombre: "La Calera" },
  { codigo: "373", nombre: "Aguazul" },
  { codigo: "375", nombre: "Arjona" },
  { codigo: "376", nombre: "Paz De Ariporo" },
  { codigo: "378", nombre: "Guaduas" },
  { codigo: "379", nombre: "Abrego" },
  { codigo: "380", nombre: "Fonseca" },
  { codigo: "381", nombre: "San Vicente del Chucuri" },
  { codigo: "383", nombre: "San Onofre" },
  { codigo: "385", nombre: "Pivijay" },
  { codigo: "386", nombre: "Pailitas" },
  { codigo: "387", nombre: "PE Velez" },
  { codigo: "388", nombre: "Chinacota" },
  { codigo: "389", nombre: "Giron" },
  { codigo: "391", nombre: "Mompox" },
  { codigo: "392", nombre: "Cali Sur" },
  { codigo: "393", nombre: "Cali Norte" },
  { codigo: "394", nombre: "Popayan Norte" },
  { codigo: "396", nombre: "Popayan Sur" },
  { codigo: "397", nombre: "Piedecuesta" },
  { codigo: "399", nombre: "Bucaramanga Centro" },
  { codigo: "400", nombre: "Valledupar Centro" },
  { codigo: "403", nombre: "Santa Marta Av. Libertador" },
  { codigo: "406", nombre: "San Vicente del Caguan" },
  { codigo: "408", nombre: "Leticia" },
  { codigo: "409", nombre: "Puerto Carreño" },
  { codigo: "410", nombre: "San Andrés Isla" },
  { codigo: "414", nombre: "Villanueva" },
  { codigo: "417", nombre: "Candelaria" },
  { codigo: "601", nombre: "Neiva" },
  { codigo: "603", nombre: "PE Purificación" },
  { codigo: "604", nombre: "PE Acacias" },
  { codigo: "605", nombre: "PE Cartagena del Chairá" },
  { codigo: "606", nombre: "PE Valle del Guamuez" },
  { codigo: "607", nombre: "PE Baranoa" },
  { codigo: "609", nombre: "PE Santa Rosa del Sur" },
  { codigo: "610", nombre: "PE Puerto Wilches" },
  { codigo: "611", nombre: "PE Tame" },
  { codigo: "612", nombre: "PE Anserma" },
  { codigo: "616", nombre: "PE Túquerres" },
  { codigo: "617", nombre: "PE Zarzal" },
  { codigo: "621", nombre: "PE Belen" },
  { codigo: "628", nombre: "PE Majagual" },
  { codigo: "637", nombre: "PE Istmina" },
  { codigo: "641", nombre: "PE Soledad Malambo" },
  { codigo: "642", nombre: "PE Cali La Casona" },
  { codigo: "643", nombre: "PE La Pintada 2" },
  { codigo: "411", nombre: "Empoderados Plus Territorial Centro" },
  { codigo: "412", nombre: "Empoderados Plus Territorial Antioquia Sur" },
  { codigo: "419", nombre: "Empoderados Plus Territorial Sur" },
  { codigo: "420", nombre: "Empoderados Plus Territorial Norte" },
  { codigo: "425", nombre: "Empoderados Plus Territorial Antioquia Norte" },
  { codigo: "426", nombre: "Empoderados Plus Territorial Centro" },
];

// Función helper para buscar ciudades
export function buscarCiudadNegocio(termino: string): CiudadNegocio[] {
  const terminoLower = termino.toLowerCase();
  return ciudadesNegocio.filter(
    (ciudad) =>
      ciudad.nombre.toLowerCase().includes(terminoLower) ||
      ciudad.codigo.includes(termino)
  );
}

